[servers]
13.49.246.166
51.20.71.37
51.20.8.223
56.228.33.163

[servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/ec2-keypair.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
